import uuid
from typing import Optional, Dict, List
from sqlalchemy.orm import Session
from fastapi import HTTPException, status

from app.models.patient import Patient
from app.schemas.patient import PatientCreate, PatientUpdate

LANGUAGE_PACKS: Dict[str, Dict[str, str]] = {
    "en": {
        "welcome": "Welcome to MediKiosk",
        "select_language": "Please select your preferred language",
        "start_session": "Start Kiosk Session",
        "end_session": "End Session & Clear Data",
        "confirm": "Confirm",
        "cancel": "Cancel",
        "back": "Back",
        "next": "Next",
        "submit": "Submit",
        "loading": "Loading, please wait...",
        "error": "An error occurred. Please try again.",
        "success": "Operation completed successfully.",
        "abha_login": "Login with ABHA Number or Aadhaar",
        "mobile_login": "Login with Mobile Number OTP",
        "enter_aadhaar": "Enter 12-digit Aadhaar Number",
        "enter_mobile": "Enter 10-digit Mobile Number",
        "enter_otp": "Enter the 6-digit OTP sent to your phone",
        "request_otp": "Send OTP",
        "verify_otp": "Verify OTP",
        "resend_otp": "Resend OTP",
        "otp_sent_success": "OTP sent successfully to your mobile number.",
        "login_success": "Authentication successful.",
        "abha_linked": "ABHA account linked successfully.",
        "phone_number": "Phone Number",
        "first_name": "First Name",
        "last_name": "Last Name",
        "dob": "Date of Birth",
        "gender": "Gender",
        "symptoms": "Please describe your health symptoms",
        "describe_symptoms": "Describe your complaints or tap the microphone to speak",
        "voice_input": "Voice Input",
        "listening": "Listening... Speak now",
        "stop_listening": "Stop Recording",
        "emergency_alert": "Emergency Alert: High risk detected",
        "urgent_care_needed": "Immediate medical attention required. Please notify staff.",
        "doctor_recommendation": "Recommended Doctor Specialties",
        "select_doctor": "Select a Doctor to Consult",
        "queue_status": "Your Queue Status",
        "token_number": "Your Token Number",
        "current_queue_position": "Current Queue Position",
        "estimated_wait_time": "Estimated Wait Time",
        "minutes": "minutes",
        "booked_appointment": "Book Appointment",
        "appointment_confirmed": "Your appointment has been confirmed.",
        "consent_prompt": "Do you consent to share health records with the consulting doctor?",
        "consent_granted": "Consent Granted",
        "consent_revoked": "Consent Revoked",
        "share_health_records": "Share Health Records",
        "general_medicine": "General Medicine",
        "cardiology": "Cardiology",
        "orthopedics": "Orthopedics",
        "pediatrics": "Pediatrics",
        "dermatology": "Dermatology",
        "gynecology": "Gynecology",
        "ent": "ENT (Ear, Nose, Throat)",
        "ayurveda": "Ayurveda (Vaidya)",
        "prescription": "Prescription",
        "medicines": "Prescribed Medicines",
        "dosage": "Dosage",
        "morning": "Morning",
        "afternoon": "Afternoon",
        "night": "Night",
        "before_food": "Before Food",
        "after_food": "After Food",
        "app_title": "MediKiosk",
        "app_subtitle": "AI Clinical Intake & ABDM Triage Portal",
        "tab_kiosk": "Self Intake Kiosk",
        "tab_dashboard": "Doctor Dashboard",
        "tab_fhir": "FHIR R4 Export",
        "ai_question_greeting": "Namaste! Welcome to MediKiosk. What health symptom or issue brings you here today?",
        "ai_question_duration": "Thank you for explaining. For how many days or hours have you been experiencing this issue?",
        "ai_question_severity": "On a scale of 1 to 10 (1 = mild, 10 = extreme), how severe is your pain or discomfort?",
        "ai_question_conditions": "Do you have any existing medical conditions like diabetes, hypertension, or heart disease?",
        "ai_question_medications": "Are you currently taking any prescription medicines or ongoing treatments?",
        "ai_critical_cardiac_alert": "🚨 CRITICAL TRIAGE ALERT: Severe cardiac / chest distress detected. Emergency protocol activated. Please proceed directly to Emergency Counter #1 immediately.",
        "ai_intake_complete": "Intake complete! Your symptoms have been recorded and the doctor has been notified.",
        "type_message_placeholder": "Type your symptoms or speak in your language...",
        "send_button": "Send Answer",
        "badge_session": "Kiosk Session Active",
        "badge_triage_normal": "Triage: Normal",
        "badge_triage_emergency": "Triage: Emergency (Red)",
        "dashboard_heading": "Clinical Triage & Patient Queue",
        "col_token": "Token",
        "col_patient_name": "Patient Name",
        "col_abha_id": "ABHA ID",
        "col_complaint": "Chief Complaint",
        "col_priority": "Triage Priority",
    },
    "hi": {
        "welcome": "मेडीकियोस्क में आपका स्वागत है",
        "select_language": "कृपया अपनी पसंदीदा भाषा चुनें",
        "start_session": "कियोस्क सत्र शुरू करें",
        "end_session": "सत्र समाप्त करें और डेटा हटाएं",
        "confirm": "पुष्टि करें",
        "cancel": "रद्द करें",
        "back": "पीछे जाएं",
        "next": "आगे बढ़ें",
        "submit": "जमा करें",
        "loading": "लोड हो रहा है, कृपया प्रतीक्षा करें...",
        "error": "एक त्रुटि हुई। कृपया पुनः प्रयास करें।",
        "success": "कार्य सफलतापूर्वक संपन्न हुआ।",
        "abha_login": "आभा नंबर या आधार से लॉगिन करें",
        "mobile_login": "मोबाइल नंबर ओटीपी से लॉगिन करें",
        "enter_aadhaar": "12 अंकों का आधार नंबर दर्ज करें",
        "enter_mobile": "10 अंकों का मोबाइल नंबर दर्ज करें",
        "enter_otp": "फोन पर भेजा गया 6 अंकों का ओटीपी दर्ज करें",
        "request_otp": "ओटीपी भेजें",
        "verify_otp": "ओटीपी सत्यापित करें",
        "resend_otp": "ओटीपी पुनः भेजें",
        "otp_sent_success": "आपके मोबाइल नंबर पर ओटीपी सफलतापूर्वक भेजा गया।",
        "login_success": "प्रमाणीकरण सफल रहा।",
        "abha_linked": "आभा खाता सफलतापूर्वक जुड़ गया।",
        "phone_number": "फ़ोन नंबर",
        "first_name": "पहला नाम",
        "last_name": "अंतिम नाम",
        "dob": "जन्म तिथि",
        "gender": "लिंग",
        "symptoms": "कृपया अपने स्वास्थ्य के लक्षणों का वर्णन करें",
        "describe_symptoms": "अपनी समस्या बताएं या बोलने के लिए माइक पर टैप करें",
        "voice_input": "ध्वनि इनपुट",
        "listening": "सुन रहे हैं... अब बोलें",
        "stop_listening": "रिकॉर्डिंग रोकें",
        "emergency_alert": "आपातकालीन चेतावनी: उच्च जोखिम पाया गया",
        "urgent_care_needed": "तत्काल चिकित्सा की आवश्यकता है। कृपया स्टाफ को सूचित करें।",
        "doctor_recommendation": "अनुशंसित डॉक्टर विशेषज्ञता",
        "select_doctor": "परामर्श के लिए डॉक्टर चुनें",
        "queue_status": "आपकी कतार की स्थिति",
        "token_number": "आपका टोकन नंबर",
        "current_queue_position": "कतार में वर्तमान स्थान",
        "estimated_wait_time": "अनुमानित प्रतीक्षा समय",
        "minutes": "मिनट",
        "booked_appointment": "अपॉइंटमेंट बुक करें",
        "appointment_confirmed": "आपका अपॉइंटमेंट पक्का हो गया है।",
        "consent_prompt": "क्या आप डॉक्टर के साथ स्वास्थ्य रिकॉर्ड साझा करने की सहमति देते हैं?",
        "consent_granted": "सहमति प्रदान की गई",
        "consent_revoked": "सहमति वापस ली गई",
        "share_health_records": "स्वास्थ्य रिकॉर्ड साझा करें",
        "general_medicine": "सामान्य चिकित्सा (जनरल मेडिसिन)",
        "cardiology": "हृदय रोग विशेषज्ञ (कार्डियोलॉजी)",
        "orthopedics": "हड्डी रोग विशेषज्ञ (ऑर्थोपेडिक्स)",
        "pediatrics": "बाल रोग विशेषज्ञ (पीडियाट्रिक्स)",
        "dermatology": "त्वचा रोग विशेषज्ञ (डर्मेटोलॉजी)",
        "gynecology": "स्त्री रोग विशेषज्ञ (गाइनेकोलॉजी)",
        "ent": "कान, नाक और गला विशेषज्ञ (ईएनटी)",
        "ayurveda": "आयुर्वेद (वैद्य)",
        "prescription": "दवा का पर्चा (प्रिस्क्रिप्शन)",
        "medicines": "निर्धारित दवाएं",
        "dosage": "खुराक",
        "morning": "सुबह",
        "afternoon": "दोपहर",
        "night": "रात",
        "before_food": "भोजन से पहले",
        "after_food": "भोजन के बाद",
        "app_title": "मेडीकियोस्क",
        "app_subtitle": "एआई नैदानिक पूछताछ एवं आभा ट्राइएज पोर्टल",
        "tab_kiosk": "सेल्फ इनटेक कियोस्क",
        "tab_dashboard": "डॉक्टर डैशबोर्ड",
        "tab_fhir": "एफएचआईआर आर4 निर्यात",
        "ai_question_greeting": "नमस्ते! मेडीकियोस्क में आपका स्वागत है। आज आप क्या लक्षण या स्वास्थ्य समस्या महसूस कर रहे हैं?",
        "ai_question_duration": "बताने के लिए धन्यवाद। आपको यह समस्या कितने दिनों या घंटों से हो रही है?",
        "ai_question_severity": "1 से 10 के पैमाने पर (1 = हल्का, 10 = असहनीय), आपका दर्द कितना गंभीर है?",
        "ai_question_conditions": "क्या आपको पहले से मधुमेह (डायबिटीज), उच्च रक्तचाप (बीपी) या हृदय रोग जैसी कोई समस्या है?",
        "ai_question_medications": "क्या आप वर्तमान में कोई नियमित दवाएं या उपचार ले रहे हैं?",
        "ai_critical_cardiac_alert": "🚨 आपातकालीन चेतावनी: गंभीर हृदय / सीने में दर्द पाया गया। आपातकालीन प्रोटोकॉल सक्रिय। कृपया तुरंत आपातकालीन काउंटर #1 पर जाएं।",
        "ai_intake_complete": "पूछताछ पूर्ण! आपके लक्षण दर्ज कर लिए गए हैं और डॉक्टर को सूचित कर दिया गया है।",
        "type_message_placeholder": "अपने लक्षण लिखें या अपनी भाषा में बोलें...",
        "send_button": "उत्तर भेजें",
        "badge_session": "कियोस्क सत्र सक्रिय",
        "badge_triage_normal": "ट्राइएज: सामान्य",
        "badge_triage_emergency": "ट्राइएज: आपातकालीन (लाल)",
        "dashboard_heading": "नैदानिक ट्राइएज एवं मरीज कतार",
        "col_token": "टोकन",
        "col_patient_name": "मरीज का नाम",
        "col_abha_id": "आभा आईडी",
        "col_complaint": "मुख्य समस्या / लक्षण",
        "col_priority": "ट्राइएज प्राथमिकता",
    },
    "mr": {
        "welcome": "मेडीकियोस्क मध्ये आपले स्वागत आहे",
        "select_language": "कृपया आपली पसंतीची भाषा निवडा",
        "start_session": "कियोस्क सत्र सुरू करा",
        "end_session": "सत्र समाप्त करा आणि डेटा पुसा",
        "confirm": "पुष्टी करा",
        "cancel": "रद्द करा",
        "back": "मागे जा",
        "next": "पुढे जा",
        "submit": "प्रस्तुत करा",
        "loading": "लोड होत आहे, कृपया प्रतीक्षा करा...",
        "error": "त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
        "success": "काम यशस्वीरित्या पूर्ण झाले.",
        "abha_login": "आभा क्रमांक किंवा आधारने लॉगिन करा",
        "mobile_login": "मोबाइल नंबर ओटीपीने लॉगिन करा",
        "enter_aadhaar": "१२ अंकी आधार क्रमांक प्रविष्ट करा",
        "enter_mobile": "१० अंकी मोबाइल क्रमांक प्रविष्ट करा",
        "enter_otp": "मोबाईलवर आलेला ६ अंकी ओटीपी प्रविष्ट करा",
        "request_otp": "ओटीपी पाठवा",
        "verify_otp": "ओटीपी पडताळा",
        "resend_otp": "ओटीपी पुन्हा पाठवा",
        "otp_sent_success": "आपल्या मोबाइल नंबरवर ओटीपी यशस्वीरित्या पाठवला आहे.",
        "login_success": "प्रमाणीकरण यशस्वी झाले.",
        "abha_linked": "आभा खाते यशस्वीरित्या जोडले गेले.",
        "phone_number": "फोन नंबर",
        "first_name": "पहिले नाव",
        "last_name": "आडनाव",
        "dob": "जन्मतारीख",
        "gender": "लिंग",
        "symptoms": "कृपया आपल्या आरोग्याची लक्षणे सांगा",
        "describe_symptoms": "आपली लक्षणे लिहा किंवा बोलण्यासाठी माइकवर टॅप करा",
        "voice_input": "व्हॉइस इनपुट",
        "listening": "ऐकत आहे... आता बोला",
        "stop_listening": "रेकॉर्डिंग थांबवा",
        "emergency_alert": "तातडीचा इशारा: उच्च धोका आढळला",
        "urgent_care_needed": "त्वरित वैद्यकीय मदतीची गरज आहे. कृपया कर्मचाऱ्यांना कळवा.",
        "doctor_recommendation": "शिफारस केलेले तज्ज्ञ डॉक्टर",
        "select_doctor": "सल्ल्यासाठी डॉक्टर निवडा",
        "queue_status": "आपली रांगेची स्थिती",
        "token_number": "आपला टोकन क्रमांक",
        "current_queue_position": "रांगेतील वर्तमान क्रमांक",
        "estimated_wait_time": "अंदाजे प्रतीक्षा वेळ",
        "minutes": "मिनिटे",
        "booked_appointment": "अपॉइंटमेंट बुक करा",
        "appointment_confirmed": "आपली अपॉइंटमेंट निश्चित झाली आहे.",
        "consent_prompt": "आपण डॉक्टरांसोबत आरोग्य नोंदी शेअर करण्यास संमती देता का?",
        "consent_granted": "संमती दिली",
        "consent_revoked": "संमती मागे घेतली",
        "share_health_records": "आरोग्य नोंदी शेअर करा",
        "general_medicine": "सामान्य औषधोपचार (जनरल मेडिसिन)",
        "cardiology": "हृदयरोगतज्ज्ञ (कार्डिओलॉजी)",
        "orthopedics": "अस्थिरोगतज्ज्ञ (ऑर्थोपेडिक्स)",
        "pediatrics": "बालरोगतज्ज्ञ (पीडियाट्रिक्स)",
        "dermatology": "त्वचारोगतज्ज्ञ (डर्मेटॉलॉजी)",
        "gynecology": "स्त्रीरोगतज्ज्ञ (गायनेकोलॉजी)",
        "ent": "कान, नाक, घसा तज्ज्ञ (ईएनटी)",
        "ayurveda": "आयुर्वेद (वैद्य)",
        "prescription": "प्रिस्क्रिप्शन",
        "medicines": "दिलेली औषधे",
        "dosage": "मात्रा / डोस",
        "morning": "सकाळी",
        "afternoon": "दुपारी",
        "night": "रात्री",
        "before_food": "जेवणापूर्वी",
        "after_food": "जेवणानंतर",
        "app_title": "मेडीकियोस्क",
        "app_subtitle": "AI क्लिनिकल इनटेक आणि आभा ट्रायज पोर्टल",
        "tab_kiosk": "सेल्फ इनटेक कियोस्क",
        "tab_dashboard": "डॉक्टर डॅशबोर्ड",
        "tab_fhir": "FHIR R4 निर्यात",
        "ai_question_greeting": "नमस्ते! मेडीकियोस्क मध्ये आपले स्वागत आहे. आज आपल्याला कोणती लक्षणे किंवा आरोग्याचा त्रास होत आहे?",
        "ai_question_duration": "सांगितल्याबद्दल धन्यवाद. हा त्रास आपल्याला किती दिवसांपासून किंवा तासांपासून होत आहे?",
        "ai_question_severity": "१ ते १० च्या प्रमाणात (१ = हलका, १० = असह्य), आपली वेदना किंवा त्रास किती तीव्र आहे?",
        "ai_question_conditions": "आपल्याला आधीपासून मधुमेह (डायबिटीज), उच्च रक्तदाब (बीपी) किंवा हृदयरोग यांसारखा काही आजार आहे का?",
        "ai_question_medications": "सध्या आपण नियमितपणे कोणती औषधे किंवा उपचार घेत आहात का?",
        "ai_critical_cardiac_alert": "🚨 तातडीचा इशारा: गंभीर हृदय / छातीत दुखण्याची लक्षणे आढळली. आपत्कालीन प्रोटोकॉल सक्रिय. कृपया त्वरित आपत्कालीन काउंटर #1 वर जा.",
        "ai_intake_complete": "माहिती पूर्ण झाली! आपली लक्षणे नोंदवली गेली आहेत आणि डॉक्टरांना कळवण्यात आले आहे.",
        "type_message_placeholder": "आपली लक्षणे लिहा किंवा आपल्या भाषेत बोला...",
        "send_button": "उत्तर पाठवा",
        "badge_session": "कियोस्क सत्र सक्रिय",
        "badge_triage_normal": "ट्रायज: सामान्य",
        "badge_triage_emergency": "ट्रायज: आपत्कालीन (लाल)",
        "dashboard_heading": "क्लिनिकल ट्रायज आणि रुग्ण रांग",
        "col_token": "टोकन",
        "col_patient_name": "रुग्णाचे नाव",
        "col_abha_id": "आभा आयडी",
        "col_complaint": "मुख्य तक्रार / लक्षणे",
        "col_priority": "ट्रायज प्राथमिकता",
    },
    "ta": {
        "welcome": "மெடிகியோஸ்கிற்கு வருக",
        "select_language": "உங்கள் விருப்ப மொழியைத் தேர்ந்தெடுக்கவும்",
        "start_session": "கியோஸ்க் அமர்வைத் தொடங்கவும்",
        "end_session": "அமர்வை முடித்து தரவை அழிக்கவும்",
        "confirm": "உறுதிப்படுத்து",
        "cancel": "ரத்து செய்",
        "back": "பின்செல்",
        "next": "அடுத்து",
        "submit": "சமர்ப்பி",
        "loading": "ஏற்றுகிறது, காத்திருக்கவும்...",
        "error": "பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
        "success": "வெற்றிகரமாக முடிந்தது.",
        "abha_login": "ABHA எண் அல்லது ஆதாரைக் கொண்டு உள்நுழைக",
        "mobile_login": "மொபைல் எண் OTP மூலம் உள்நுழைக",
        "enter_aadhaar": "12 இலக்க ஆதார் எண்ணை உள்ளிடவும்",
        "enter_mobile": "10 இலக்க மொபைல் எண்ணை உள்ளிடவும்",
        "enter_otp": "மொபைலுக்கு வந்த 6 இலக்க OTP-யை உள்ளிடவும்",
        "request_otp": "OTP அனுப்பு",
        "verify_otp": "OTP சரிபார்க்கவும்",
        "resend_otp": "OTP மீண்டும் அனுப்பு",
        "otp_sent_success": "உங்கள் மொபைலுக்கு OTP வெற்றிகரமாக அனுப்பப்பட்டது.",
        "login_success": "உள்நுழைவு வெற்றிகரமானது.",
        "abha_linked": "ABHA கணக்கு வெற்றிகரமாக இணைக்கப்பட்டது.",
        "phone_number": "தொலைபேசி எண்",
        "first_name": "முதல் பெயர்",
        "last_name": "கடைசி பெயர்",
        "dob": "பிறந்த தேதி",
        "gender": "பாலினம்",
        "symptoms": "உங்கள் சுகாதார அறிகுறிகளை விவரிக்கவும்",
        "describe_symptoms": "அறிகுறிகளை தட்டச்சு செய்க அல்லது பேச மைக் தொடவும்",
        "voice_input": "குரல் உள்ளீடு",
        "listening": "கேட்கிறது... இப்போது பேசுங்கள்",
        "stop_listening": "பதிவை நிறுத்து",
        "emergency_alert": "அவசர எச்சரிக்கை: அதிக ஆபத்து கண்டறியப்பட்டது",
        "urgent_care_needed": "உடனடி மருத்துவ கவனிப்பு தேவை. ஊழியர்களுக்கு தெரிவிக்கவும்.",
        "doctor_recommendation": "பரிந்துரைக்கப்பட்ட மருத்துவர்கள்",
        "select_doctor": "மருத்துவரைத் தேர்ந்தெடுக்கவும்",
        "queue_status": "உங்கள் வரிசை நிலை",
        "token_number": "டோக்கன் எண்",
        "current_queue_position": "தற்போதைய வரிசை நிலை",
        "estimated_wait_time": "மதிப்பிடப்பட்ட காத்திருப்பு நேரம்",
        "minutes": "நிமிடங்கள்",
        "booked_appointment": "முன்பதிவு செய்",
        "appointment_confirmed": "முன்பதிவு உறுதி செய்யப்பட்டது.",
        "consent_prompt": "மருத்துவருடன் சுகாதார பதிவுகளைப் பகிர ஒப்புதல் அளிக்கிறீர்களா?",
        "consent_granted": "ஒப்புதல் அளிக்கப்பட்டது",
        "consent_revoked": "ஒப்புதல் ரத்து செய்யப்பட்டது",
        "share_health_records": "சுகாதார பதிவுகளைப் பகிரவும்",
        "general_medicine": "பொது மருத்துவம் (General Medicine)",
        "cardiology": "இதய நோய் மருத்துவம் (Cardiology)",
        "orthopedics": "எலும்பியல் மருத்துவம் (Orthopedics)",
        "pediatrics": "குழந்தைகள் நலம் (Pediatrics)",
        "dermatology": "தோல் மருத்துவம் (Dermatology)",
        "gynecology": "மகளிர் மருத்துவம் (Gynecology)",
        "ent": "காது, மூக்கு, தொண்டை (ENT)",
        "ayurveda": "ஆயுர்வேதம் (வைத்தியர்)",
        "prescription": "மருந்துச் சீட்டு (Prescription)",
        "medicines": "பரிந்துரைக்கப்பட்ட மருந்துகள்",
        "dosage": "அளவு (Dosage)",
        "morning": "காலை",
        "afternoon": "மதியம்",
        "night": "இரவு",
        "before_food": "உணவுக்கு முன்",
        "after_food": "உணவுக்கு பின்",
        "app_title": "மெடிகியோஸ்க்",
        "app_subtitle": "AI மருத்துவ பரிசோதனை மற்றும் ABDM போர்டல்",
        "tab_kiosk": "சுய பரிசோதனை கியோஸ்க்",
        "tab_dashboard": "மருத்துவர் தகவல் பலகை",
        "tab_fhir": "FHIR R4 ஏற்றுமதி",
        "ai_question_greeting": "வணக்கம்! மெடிகியோஸ்கிற்கு வருக. இன்று உங்களுக்கு என்ன சுகாதார பிரச்சினை அல்லது அறிகுறிகள் உள்ளன?",
        "ai_question_duration": "பகிர்ந்ததற்கு நன்றி. இந்த பிரச்சினை எத்தனை நாட்களாக அல்லது மணிகளாக உள்ளது?",
        "ai_question_severity": "1 முதல் 10 வரை (1 = லேசானது, 10 = தாங்க முடியாதது), உங்கள் வலி எவ்வளவு தீவிரமானது?",
        "ai_question_conditions": "உங்களுக்கு சர்க்கரை நோய், உயர் ரத்த அழுத்தம் அல்லது இதய நோய் போன்ற பிற பிரச்சினைகள் உள்ளதா?",
        "ai_question_medications": "நீங்கள் தற்போது ஏதேனும் வழக்கமான மருந்துகள் எடுத்துக்கொள்கிறீர்களா?",
        "ai_critical_cardiac_alert": "🚨 அவசர எச்சரிக்கை: தீவிர நெஞ்சு வலி கண்டறியப்பட்டது. அவசர நெறிமுறை செயல்படுத்தப்பட்டது. உடனடியாக அவசர பிரிவு #1-க்கு செல்லவும்.",
        "ai_intake_complete": "பரிசோதனை முடிந்தது! உங்கள் அறிகுறிகள் பதிவு செய்யப்பட்டு மருத்துவருக்கு தெரிவிக்கப்பட்டுள்ளது.",
        "type_message_placeholder": "உங்கள் அறிகுறிகளை தட்டச்சு செய்யவும் அல்லது பேசவும்...",
        "send_button": "பதிலை அனுப்பு",
        "badge_session": "கியோஸ்க் அமர்வு செயலில் உள்ளது",
        "badge_triage_normal": "முன்னுரிமை: சாதாரண",
        "badge_triage_emergency": "முன்னுரிமை: அவசரம் (சிவப்பு)",
        "dashboard_heading": "மருத்துவ முன்னுரிமை மற்றும் நோயாளி வரிசை",
        "col_token": "டோக்கன்",
        "col_patient_name": "நோயாளி பெயர்",
        "col_abha_id": "ABHA ஐடி",
        "col_complaint": "முக்கிய பிரச்சினை",
        "col_priority": "முன்னுரிமை நிலை",
    },
    "te": {
        "welcome": "మెడికియోస్క్‌కి స్వాగతం",
        "select_language": "మీ ప్రాధాన్యత భాషను ఎంచుకోండి",
        "start_session": "కియోస్క్ సెషన్ ప్రారంభించండి",
        "end_session": "సెషన్ ముగించి డేటాను తొలగించండి",
        "confirm": "నిర్ధారించండి",
        "cancel": "రద్దు చేయండి",
        "back": "వెనుకకు",
        "next": "తదుపరి",
        "submit": "సమర్పించండి",
        "loading": "లోడ్ అవుతోంది, దయచేసి వేచి ఉండండి...",
        "error": "లోపం సంభవించింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
        "success": "విజయవంతంగా పూర్తయింది.",
        "abha_login": "ABHA లేదా ఆధార్‌తో లాగిన్ చేయండి",
        "mobile_login": "మొబైల్ నంబర్ OTPతో లాగిన్ చేయండి",
        "enter_aadhaar": "12 అంకెల ఆధార్ నంబర్ నమోదు చేయండి",
        "enter_mobile": "10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి",
        "enter_otp": "ఫోన్‌కు పంపిన 6 అంకెల OTP నమోదు చేయండి",
        "request_otp": "OTP పంపండి",
        "verify_otp": "OTP ధృవీకరించండి",
        "resend_otp": "OTPని మళ్లీ పంపండి",
        "otp_sent_success": "మీ మొబైల్ నంబర్‌కు OTP విజయవంతంగా పంపబడింది.",
        "login_success": "లాగిన్ విజయవంతమైంది.",
        "abha_linked": "ABHA ఖాతా విజయవంతంగా లింక్ చేయబడింది.",
        "phone_number": "ఫోన్ నంబర్",
        "first_name": "మొదటి పేరు",
        "last_name": "చివరి పేరు",
        "dob": "పుట్టిన తేదీ",
        "gender": "లింగం",
        "symptoms": "మీ ఆరోగ్య లక్షణాలను వివరించండి",
        "describe_symptoms": "లక్షణాలను టైప్ చేయండి లేదా మాట్లాడటానికి మైక్ నొక్కండి",
        "voice_input": "వాయిస్ ఇన్‌పుట్",
        "listening": "వింటోంది... ఇప్పుడు మాట్లాడండి",
        "stop_listening": "రికార్డింగ్ ఆపండి",
        "emergency_alert": "అత్యవసర హెచ్చరిక: అధిక ప్రమాదం గుర్తించబడింది",
        "urgent_care_needed": "తక్షణ వైద్య సహాయం అవసరం. దయచేసి సిబ్బందికి తెలియజేయండి.",
        "doctor_recommendation": "సిఫార్సు చేసిన వైద్య నిపుణులు",
        "select_doctor": "డాక్టర్‌ను ఎంచుకోండి",
        "queue_status": "మీ క్యూ స్థితి",
        "token_number": "మీ టోకెన్ నంబర్",
        "current_queue_position": "క్యూలో ప్రస్తుత స్థానం",
        "estimated_wait_time": "వేచి ఉండే సమయం",
        "minutes": "నిమిషాలు",
        "booked_appointment": "అపాయింట్‌మెంట్ బుక్ చేయండి",
        "appointment_confirmed": "మీ అపాయింట్‌మెంట్ నిర్ధారించబడింది.",
        "consent_prompt": "డాక్టర్‌తో ఆరోగ్య రికార్డులను పంచుకోవడానికి సమ్మతిస్తున్నారా?",
        "consent_granted": "సమ్మతి ఇవ్వబడింది",
        "consent_revoked": "సమ్మతి రద్దు చేయబడింది",
        "share_health_records": "ఆరోగ్య రికార్డులను పంచుకోండి",
        "general_medicine": "జనరల్ మెడిసిన్",
        "cardiology": "కార్డియాలజీ (గుండె నిపుణులు)",
        "orthopedics": "ఆర్థోపెడిక్స్ (ఎముకల నిపుణులు)",
        "pediatrics": "పీడియాట్రిక్స్ (పిల్లల వైద్యులు)",
        "dermatology": "డెర్మటాలజీ (చర్మ నిపుణులు)",
        "gynecology": "గైనకాలజీ (స్త్రీల నిపుణులు)",
        "ent": "ఈఎన్‌టీ (చెవి, ముక్కు, గొంతు)",
        "ayurveda": "ఆయుర్వేదం (వైద్యులు)",
        "prescription": "ప్రిస్క్రిప్షన్",
        "medicines": "సూచించిన మందులు",
        "dosage": "మోతాదు",
        "morning": "ఉదయం",
        "afternoon": "మధ్యాహ్నం",
        "night": "రాత్రి",
        "before_food": "భోజనానికి ముందు",
        "after_food": "భోజనం తర్వాత",
        "app_title": "మెడికియోస్క్",
        "app_subtitle": "AI క్లినికల్ ఇన్‌టేక్ & ABDM ట్రయేజ్ పోర్టల్",
        "tab_kiosk": "సెల్ఫ్ ఇన్‌టేక్ కియోస్క్",
        "tab_dashboard": "డాక్టర్ డాష్‌బోర్డ్",
        "tab_fhir": "FHIR R4 ఎగుమతి",
        "ai_question_greeting": "నమస్తే! మెడికియోస్క్‌కి స్వాగతం. ఈరోజు మీకు ఎలాంటి ఆరోగ్య సమస్య లేదా లక్షణాలు ఉన్నాయి?",
        "ai_question_duration": "తెలిపినందుకు ధన్యవాదాలు. ఈ సమస్య మీకు ఎన్ని రోజులుగా లేదా గంటలుగా ఉంది?",
        "ai_question_severity": "1 నుండి 10 స్కేలులో (1 = తక్కువ, 10 = భరించలేనిది), మీ నొప్పి ఎంత తీవ్రంగా ఉంది?",
        "ai_question_conditions": "మీకు గతంలో మధుమేహం, బీపీ లేదా గుండె సమస్యలు వంటి వ్యాధులు ఏమైనా ఉన్నాయా?",
        "ai_question_medications": "మీరు ప్రస్తుతం ఏవైనా రోజువారీ మందులు తీసుకుంటున్నారా?",
        "ai_critical_cardiac_alert": "🚨 అత్యవసర హెచ్చరిక: తీవ్రమైన గుండె / ఛాతీ నొప్పి గుర్తించబడింది. దయచేసి వెంటనే ఎమర్జెన్సీ కౌంటర్ #1 కి వెళ్ళండి.",
        "ai_intake_complete": "వివరాల నమోదు పూర్తయింది! మీ లక్షణాలు రికార్డ్ చేయబడ్డాయి మరియు వైద్యుడికి తెలియజేయబడింది.",
        "type_message_placeholder": "మీ లక్షణాలను టైప్ చేయండి లేదా మాట్లాడండి...",
        "send_button": "సమాధానం పంపండి",
        "badge_session": "కియోస్క్ సెషన్ సక్రియంగా ఉంది",
        "badge_triage_normal": "ట్రయేజ్: సాధారణ",
        "badge_triage_emergency": "ట్రయేజ్: అత్యవసరం (ఎరుపు)",
        "dashboard_heading": "క్లినికల్ ట్రయేజ్ & రోగుల క్యూ",
        "col_token": "టోకెన్",
        "col_patient_name": "రోగి పేరు",
        "col_abha_id": "ABHA ఐడీ",
        "col_complaint": "ప్రధాన సమస్య",
        "col_priority": "ట్రయేజ్ ప్రాధాన్యత",
    },
    "kn": {
        "welcome": "ಮೆಡಿಕಿಯೋಸ್ಕ್‌ಗೆ ಸುಸ್ವಾಗತ",
        "select_language": "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        "start_session": "ಕಿಯೋಸ್ಕ್ ಅವಧಿ ಪ್ರಾರಂಭಿಸಿ",
        "end_session": "ಅವಧಿ ಮುಗಿಸಿ ಡೇಟಾ ತೆರವುಗೊಳಿಸಿ",
        "confirm": "ದೃಢೀಕರಿಸಿ",
        "cancel": "ರದ್ದುಮಾಡಿ",
        "back": "ಹಿಂದಕ್ಕೆ",
        "next": "ಮುಂದೆ",
        "submit": "ಸಲ್ಲಿಸಿ",
        "loading": "ಲೋಡ್ ಆಗುತ್ತಿದೆ, ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ...",
        "error": "ದೋಷ ಸಂಭವಿಸಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
        "success": "ಕಾರ್ಯ ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಂಡಿದೆ.",
        "abha_login": "ABHA ಸಂಖ್ಯೆ ಅಥವಾ ಆಧಾರ್‌ನೊಂದಿಗೆ ಲಾಗಿನ್ ಮಾಡಿ",
        "mobile_login": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ OTP ಯೊಂದಿಗೆ ಲಾಗಿನ್ ಮಾಡಿ",
        "enter_aadhaar": "12 ಅಂಕಿಗಳ ಆಧಾರ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
        "enter_mobile": "10 ಅಂಕಿಗಳ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
        "enter_otp": "ಮೊಬೈಲ್‌ಗೆ ಕಳುಹಿಸಲಾದ 6 ಅಂಕಿಗಳ OTP ನಮೂದಿಸಿ",
        "request_otp": "OTP ಕಳುಹಿಸಿ",
        "verify_otp": "OTP ಪರಿಶೀಲಿಸಿ",
        "resend_otp": "OTP ಮರುಕಳುಹಿಸಿ",
        "otp_sent_success": "ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗೆ OTP ಯಶಸ್ವಿಯಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ.",
        "login_success": "ದೃಢೀಕರಣ ಯಶಸ್ವಿಯಾಗಿದೆ.",
        "abha_linked": "ABHA ಖಾತೆ ಯಶಸ್ವಿಯಾಗಿ ಲಿಂಕ್ ಆಗಿದೆ.",
        "phone_number": "ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
        "first_name": "ಮೊದಲ ಹೆಸರು",
        "last_name": "ಕೊನೆಯ ಹೆಸರು",
        "dob": "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
        "gender": "ಲಿಂಗ",
        "symptoms": "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಆರೋಗ್ಯ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ",
        "describe_symptoms": "ಲಕ್ಷಣಗಳನ್ನು ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ಮಾತನಾಡಲು ಮೈಕ್ ಒತ್ತಿರಿ",
        "voice_input": "ಧ್ವನಿ ಇನ್‌ಪುಟ್",
        "listening": "ಆಲಿಸುತ್ತಿದೆ... ಈಗ ಮಾತನಾಡಿ",
        "stop_listening": "ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ",
        "emergency_alert": "ತುರ್ತು ಎಚ್ಚರಿಕೆ: ಗಂಭೀರ ಅಪಾಯ ಪತ್ತೆಯಾಗಿದೆ",
        "urgent_care_needed": "ತಕ್ಷಣದ ವೈದ್ಯಕೀಯ ನೆರವು ಅಗತ್ಯವಿದೆ. ದಯವಿಟ್ಟು ಸಿಬ್ಬಂದಿಗೆ ತಿಳಿಸಿ.",
        "doctor_recommendation": "ಶಿಫಾರಸು ಮಾಡಿದ ವೈದ್ಯಕೀಯ ತಜ್ಞರು",
        "select_doctor": "ವೈದ್ಯರನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        "queue_status": "ನಿಮ್ಮ ಸರತಿ ಸಾಲಿನ ಸ್ಥಿತಿ",
        "token_number": "ನಿಮ್ಮ ಟೋಕನ್ ಸಂಖ್ಯೆ",
        "current_queue_position": "ಪ್ರಸ್ತುತ ಸಾಲಿನ ಸ್ಥಾನ",
        "estimated_wait_time": "ಅಂದಾಜು ಕಾಯುವ ಸಮಯ",
        "minutes": "ನಿಮಿಷಗಳು",
        "booked_appointment": "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ",
        "appointment_confirmed": "ನಿಮ್ಮ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಖಚಿತಪಟ್ಟಿದೆ.",
        "consent_prompt": "ವೈದ್ಯರೊಂದಿಗೆ ಆರೋಗ್ಯ ದಾಖಲೆಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಲು ನೀವು ಸಮ್ಮತಿಸುತ್ತೀರಾ?",
        "consent_granted": "ಸಮ್ಮತಿ ನೀಡಲಾಗಿದೆ",
        "consent_revoked": "ಸಮ್ಮತಿ ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ",
        "share_health_records": "ಆರೋಗ್ಯ ದಾಖಲೆಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ",
        "general_medicine": "ಸಾಮಾನ್ಯ ಔಷಧ (ಜನರಲ್ ಮೆಡಿಸಿನ್)",
        "cardiology": "ಹೃದ್ರೋಗ ತಜ್ಞರು (ಕಾರ್ಡಿಯಾಲಜಿ)",
        "orthopedics": "ಮೂಳೆ ತಜ್ಞರು (ಆರ್ಥೋಪೆಡಿಕ್ಸ್)",
        "pediatrics": "ಮಕ್ಕಳ ತಜ್ಞರು (ಪೀಡಿಯಾಟ್ರಿಕ್ಸ್)",
        "dermatology": "ಚರ್ಮರೋಗ ತಜ್ಞರು (ಡರ್ಮಟಾಲಜಿ)",
        "gynecology": "ಸ್ತ್ರೀರೋಗ ತಜ್ಞರು (ಗೈನೆಕಾಲಜಿ)",
        "ent": "ಕಿವಿ, ಮೂಗು, ಗಂಟಲು (ಇಎನ್‌ಟಿ)",
        "ayurveda": "ಆಯುರ್ವೇದ (ವೈದ್ಯ)",
        "prescription": "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್",
        "medicines": "ಔಷಧಿಗಳು",
        "dosage": "ಪ್ರಮಾಣ (ಡೋಸ್)",
        "morning": "ಬೆಳಿಗ್ಗೆ",
        "afternoon": "ಮಧ್ಯಾಹ್ನ",
        "night": "ರಾತ್ರಿ",
        "before_food": "ಊಟಕ್ಕೆ ಮುಂಚೆ",
        "after_food": "ಊಟದ ನಂತರ",
        "app_title": "ಮೆಡಿಕಿಯೋಸ್ಕ್",
        "app_subtitle": "AI ಕ್ಲಿನಿಕಲ್ ಇನ್‌ಟೇಕ್ ಮತ್ತು ABDM ಟ್ರಯೇಜ್ ಪೋರ್ಟಲ್",
        "tab_kiosk": "ಸ್ವಯಂ ತಪಾಸಣಾ ಕಿಯೋಸ್ಕ್",
        "tab_dashboard": "ವೈದ್ಯರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "tab_fhir": "FHIR R4 ರಫ್ತು",
        "ai_question_greeting": "ನಮಸ್ಕಾರ! ಮೆಡಿಕಿಯೋಸ್ಕ್‌ಗೆ ಸುಸ್ವಾಗತ. ಇಂದು ನೀವು ಯಾವ ಆರೋಗ್ಯ ಸಮಸ್ಯೆ ಅಥವಾ ಲಕ್ಷಣಗಳನ್ನು ಎದುರಿಸುತ್ತಿದ್ದೀರಿ?",
        "ai_question_duration": "ತಿಳಿಸಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು. ಈ ಸಮಸ್ಯೆ ಎಷ್ಟು ದಿನಗಳಿಂದ ಅಥವಾ ಗಂಟೆಗಳಿಂದ ಇದೆ?",
        "ai_question_severity": "1 ರಿಂದ 10 ರ ಪ್ರಮಾಣದಲ್ಲಿ (1 = ಸೌಮ್ಯ, 10 = ಅಸಹನೀಯ), ನಿಮ್ಮ ನೋವು ಎಷ್ಟು ತೀವ್ರವಾಗಿದೆ?",
        "ai_question_conditions": "ನಿಮಗೆ ಮಧುಮೇಹ, ಅಧಿಕ ರಕ್ತದೊತ್ತಡ ಅಥವಾ ಹೃದ್ರೋಗದಂತಹ ಹಿಂದಿನ ಆರೋಗ್ಯ ಸಮಸ್ಯೆಗಳಿವೆಯೇ?",
        "ai_question_medications": "ನೀವು ಪ್ರಸ್ತುತ ಯಾವುದೇ ದೈನಂದಿನ ಔಷಧಿಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳುತ್ತಿದ್ದೀರಾ?",
        "ai_critical_cardiac_alert": "🚨 ತುರ್ತು ಎಚ್ಚರಿಕೆ: ಗಂಭೀರ ಹೃದಯ / ಎದೆ ನೋವು ಪತ್ತೆಯಾಗಿದೆ. ದಯವಿಟ್ಟು ತಕ್ಷಣ ತುರ್ತು ಕೌಂಟರ್ #1 ಕ್ಕೆ ತೆರಳಿ.",
        "ai_intake_complete": "ಮಾಹಿತಿ ಪೂರ್ಣಗೊಂಡಿದೆ! ನಿಮ್ಮ ಲಕ್ಷಣಗಳು ದಾಖಲಾಗಿವೆ ಮತ್ತು ವೈದ್ಯರಿಗೆ ತಿಳಿಸಲಾಗಿದೆ.",
        "type_message_placeholder": "ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ಬರೆಯಿರಿ ಅಥವಾ ಮಾತನಾಡಿ...",
        "send_button": "ಉತ್ತರ ಕಳುಹಿಸಿ",
        "badge_session": "ಕಿಯೋಸ್ಕ್ ಅವಧಿ ಸಕ್ರಿಯವಾಗಿದೆ",
        "badge_triage_normal": "ಟ್ರಯೇಜ್: ಸಾಮಾನ್ಯ",
        "badge_triage_emergency": "ಟ್ರಯೇಜ್: ತುರ್ತು (ಕೆಂಪು)",
        "dashboard_heading": "ಕ್ಲಿನಿಕಲ್ ಟ್ರಯೇಜ್ ಮತ್ತು ರೋಗಿಗಳ ಸರತಿ ಸಾಲು",
        "col_token": "ಟೋಕನ್",
        "col_patient_name": "ರೋಗಿಯ ಹೆಸರು",
        "col_abha_id": "ABHA ಐಡಿ",
        "col_complaint": "ಮುಖ್ಯ ದೂರು / ಲಕ್ಷಣ",
        "col_priority": "ಟ್ರಯೇಜ್ ಆದ್ಯತೆ",
    },
    "bn": {
        "welcome": "মেডিকিয়স্কে আপনাকে স্বাগতম",
        "select_language": "অনুগ্রহ করে আপনার পছন্দের ভাষা নির্বাচন করুন",
        "start_session": "কিয়স্ক সেশন শুরু করুন",
        "end_session": "সেশন শেষ করুন এবং ডেটা সাফ করুন",
        "confirm": "নিশ্চিত করুন",
        "cancel": "বাতিল করুন",
        "back": "পেছনে যান",
        "next": "পরবর্তী",
        "submit": "জমা দিন",
        "loading": "লোড হচ্ছে, অনুগ্রহ করে অপেক্ষা করুন...",
        "error": "একটি ত্রুটি ঘটেছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
        "success": "কাজটি সফলভাবে সম্পন্ন হয়েছে।",
        "abha_login": "আভা নম্বর বা আধার দিয়ে লগইন করুন",
        "mobile_login": "মোবাইল নম্বর ওটিপি দিয়ে লগইন করুন",
        "enter_aadhaar": "১২ সংখ্যার আধার নম্বর লিখুন",
        "enter_mobile": "১০ সংখ্যার মোবাইল নম্বর লিখুন",
        "enter_otp": "ফোনে পাঠানো ৬ সংখ্যার ওটিপি লিখুন",
        "request_otp": "ওটিপি পাঠান",
        "verify_otp": "ওটিপি যাচাই করুন",
        "resend_otp": "ওটিপি পুনরায় পাঠান",
        "otp_sent_success": "আপনার মোবাইল নম্বরে ওটিপি সফলভাবে পাঠানো হয়েছে।",
        "login_success": "লগইন সফল হয়েছে।",
        "abha_linked": "আভা অ্যাকাউন্ট সফলভাবে যুক্ত হয়েছে।",
        "phone_number": "ফোন নম্বর",
        "first_name": "নামের প্রথম অংশ",
        "last_name": "পদবি",
        "dob": "জন্ম তারিখ",
        "gender": "লিঙ্গ",
        "symptoms": "অনুগ্রহ করে আপনার স্বাস্থ্য সমস্যার লক্ষণগুলি বর্ণনা করুন",
        "describe_symptoms": "আপনার লক্ষণগুলি লিখুন বা কথা বলতে মাইক ট্যাপ করুন",
        "voice_input": "ভয়েস ইনপুট",
        "listening": "শুনছি... এখন কথা বলুন",
        "stop_listening": "রেকর্ডিং বন্ধ করুন",
        "emergency_alert": "জরুরি সতর্কতা: উচ্চ ঝুঁকি চিহ্নিত হয়েছে",
        "urgent_care_needed": "অবিলম্বে চিকিৎসার প্রয়োজন। অনুগ্রহ করে কর্মীদের জানান।",
        "doctor_recommendation": "প্রস্তাবিত বিশেষজ্ঞ ডাক্তার",
        "select_doctor": "পরামর্শের জন্য ডাক্তার নির্বাচন করুন",
        "queue_status": "আপনার লাইনের অবস্থা",
        "token_number": "আপনার টোকেন নম্বর",
        "current_queue_position": "লাইনে বর্তমান অবস্থান",
        "estimated_wait_time": "আনুমানিক অপেক্ষার সময়",
        "minutes": "মিনিট",
        "booked_appointment": "অ্যাপয়েন্টমেন্ট বুক করুন",
        "appointment_confirmed": "আপনার অ্যাপয়েন্টমেন্ট নিশ্চিত হয়েছে।",
        "consent_prompt": "আপনি কি ডাক্তারের সাথে স্বাস্থ্য রেকর্ড শেয়ার করতে সম্মত?",
        "consent_granted": "সম্মতি দেওয়া হয়েছে",
        "consent_revoked": "সম্মতি প্রত্যাহার করা হয়েছে",
        "share_health_records": "স্বাস্থ্য রেকর্ড শেয়ার করুন",
        "general_medicine": "সাধারণ চিকিৎসা (জেনারেল মেডিসিন)",
        "cardiology": "হৃদরোগ বিশেষজ্ঞ (কার্ডিওলজি)",
        "orthopedics": "অস্থিরোগ বিশেষজ্ঞ (অর্থোপেডিকস)",
        "pediatrics": "শিশুরোগ বিশেষজ্ঞ (পেডিয়াট্রিকস)",
        "dermatology": "চর্মরোগ বিশেষজ্ঞ (ডার্মাটোলজি)",
        "gynecology": "স্ত্রীরোগ বিশেষজ্ঞ (গাইনোকোলজি)",
        "ent": "কান, নাক ও গলা (ইএনটি)",
        "ayurveda": "আয়ুর্বেদ (বৈদ্য)",
        "prescription": "প্রেসক্রিপশন",
        "medicines": "নির্ধারিত ওষুধ",
        "dosage": "মাত্রা (ডোজ)",
        "morning": "সকাল",
        "afternoon": "দুপুর",
        "night": "রাত",
        "before_food": "খাবারের আগে",
        "after_food": "খাবারের পরে",
        "app_title": "মেডিকিয়স্ক",
        "app_subtitle": "এআই ক্লিনিকাল ইনটেক এবং আভা ট্রায়াজ পোর্টাল",
        "tab_kiosk": "সেলফ ইনটেক কিয়স্ক",
        "tab_dashboard": "ডাক্তার ড্যাশবোর্ড",
        "tab_fhir": "এফএইচআইআর আর৪ এক্সপোর্ট",
        "ai_question_greeting": "নমস্কার! মেডিকিয়স্কে আপনাকে স্বাগতম। আজ আপনার কী কী স্বাস্থ্য সমস্যা বা লক্ষণ দেখা দিচ্ছে?",
        "ai_question_duration": "জানানোর জন্য ধন্যবাদ। এই সমস্যাটি আপনার কত দিন বা ঘণ্টা ধরে হচ্ছে?",
        "ai_question_severity": "১ থেকে ১০ এর স্কেলে (১ = মৃদু, ১০ = অসহ্য), আপনার ব্যথা বা কষ্ট কতটা তীব্র?",
        "ai_question_conditions": "আপনার কি ডায়াবেটিস, উচ্চ রক্তচাপ বা হৃদরোগের মতো কোনো পূর্ব রোগ আছে?",
        "ai_question_medications": "আপনি কি বর্তমানে কোনো নিয়মিত ওষুধ গ্রহণ করছেন?",
        "ai_critical_cardiac_alert": "🚨 জরুরি সতর্কতা: গুরুতর হার্ট / বুকে ব্যথার লক্ষণ চিহ্নিত। অবিলম্বে জরুরি কাউন্টার #১-এ যান।",
        "ai_intake_complete": "ইনটেক সম্পন্ন! আপনার লক্ষণগুলি নথিভুক্ত করা হয়েছে এবং ডাক্তারকে জানানো হয়েছে।",
        "type_message_placeholder": "আপনার লক্ষণগুলি লিখুন বা আপনার ভাষায় বলুন...",
        "send_button": "উত্তর পাঠান",
        "badge_session": "কিয়স্ক সেশন সক্রিয়",
        "badge_triage_normal": "ট্রায়াজ: সাধারণ",
        "badge_triage_emergency": "ট্রায়াজ: জরুরি (লাল)",
        "dashboard_heading": "ক্লিনিকাল ট্রায়াজ এবং রোগীর লাইন",
        "col_token": "টোকেন",
        "col_patient_name": "রোগীর নাম",
        "col_abha_id": "আভা আইডি",
        "col_complaint": "প্রধান সমস্যা / লক্ষণ",
        "col_priority": "ট্রায়াজ অগ্রাধিকার",
    },
}


def register_patient(db: Session, patient_in: PatientCreate) -> Patient:
    # Check if ABHA ID already exists if provided
    if patient_in.abha_id:
        existing = db.query(Patient).filter(Patient.abha_id == patient_in.abha_id).first()
        if existing:
            return existing

    patient = Patient(
        first_name=patient_in.first_name,
        last_name=patient_in.last_name,
        date_of_birth=patient_in.date_of_birth,
        gender=patient_in.gender,
        phone=patient_in.phone,
        email=patient_in.email,
        address=patient_in.address,
        emergency_contact_name=patient_in.emergency_contact_name,
        emergency_contact_phone=patient_in.emergency_contact_phone,
        preferred_language=patient_in.preferred_language or "en",
        abha_id=patient_in.abha_id,
        abha_address=patient_in.abha_address,
    )
    db.add(patient)
    db.commit()
    db.refresh(patient)
    return patient


def get_patient(db: Session, patient_id: uuid.UUID) -> Patient:
    patient = db.query(Patient).filter(Patient.id == patient_id).first()
    if not patient:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Patient with ID '{patient_id}' not found",
        )
    return patient


def update_patient(db: Session, patient_id: uuid.UUID, patient_in: PatientUpdate) -> Patient:
    patient = get_patient(db, patient_id)
    update_data = patient_in.model_dump(exclude_unset=True)
    for field, value in update_data.items():
        setattr(patient, field, value)
    db.commit()
    db.refresh(patient)
    return patient


def update_preferred_language(db: Session, patient_id: uuid.UUID, language_code: str) -> Patient:
    patient = get_patient(db, patient_id)
    patient.preferred_language = language_code
    db.commit()
    db.refresh(patient)
    return patient


def get_language_pack(language_code: str) -> Dict[str, str]:
    return LANGUAGE_PACKS.get(language_code.lower(), LANGUAGE_PACKS["en"])


def get_supported_languages() -> List[Dict[str, str]]:
    return [
        {"code": "en", "name": "English"},
        {"code": "hi", "name": "Hindi (हिंदी)"},
        {"code": "mr", "name": "Marathi (मराठी)"},
        {"code": "ta", "name": "Tamil (தமிழ்)"},
        {"code": "te", "name": "Telugu (తెలుగు)"},
        {"code": "kn", "name": "Kannada (ಕನ್ನಡ)"},
        {"code": "bn", "name": "Bengali (বাংলা)"},
    ]


def translate_text(text: str, target_language: str, source_language: str = "en") -> str:
    """
    Translates medical terms, clinical phrases, triage statuses, and UI strings
    into any of the supported Indian languages.
    """
    tgt = target_language.lower().strip()
    src = source_language.lower().strip()

    if tgt == src or not text:
        return text

    target_pack = LANGUAGE_PACKS.get(tgt)
    if not target_pack:
        return text

    clean_text = text.strip()
    clean_lower = clean_text.lower()

    # 1. Direct match by translation key
    if clean_lower in target_pack:
        return target_pack[clean_lower]

    # Normalize key with underscores (e.g. "general medicine" -> "general_medicine")
    underscore_key = clean_lower.replace(" ", "_").replace("-", "_")
    if underscore_key in target_pack:
        return target_pack[underscore_key]

    # 2. Match by English value (case-insensitive)
    en_pack = LANGUAGE_PACKS["en"]
    for key, en_val in en_pack.items():
        if en_val.lower() == clean_lower:
            return target_pack.get(key, text)

    # 3. If source is non-English, find canonical key in source pack
    if src != "en" and src in LANGUAGE_PACKS:
        source_pack = LANGUAGE_PACKS[src]
        for key, src_val in source_pack.items():
            if src_val.lower() == clean_lower:
                return target_pack.get(key, text)

    # 4. Phrase-level matching: check if any key phrase exists inside text
    translated = text
    for key, en_val in sorted(en_pack.items(), key=lambda x: len(x[1]), reverse=True):
        if len(en_val) > 3 and en_val.lower() in clean_lower:
            tgt_val = target_pack.get(key)
            if tgt_val:
                # case-insensitive replace of first occurrence
                import re
                translated = re.sub(re.escape(en_val), tgt_val, translated, flags=re.IGNORECASE)

    return translated

